name: AWS SAM CI/CD Workflow
on: push
env:
  REGION: ap-south-1
  TESTING_ARTIFACTS_BUCKET: sam-test-ci-cd
jobs:
  validate-and-package:
    if: github.ref == 'refs/heads/main'
    environment: dev
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${env.REGION}
      - uses: aws-actions/setup-sam@v1
      - run: sam validate -t template.json
      - name: package sam application
        run: |
          sam package \
          --s3-bucket ${TESTING_ARTIFACTS_BUCKET} \
          --region ${REGION} \
          --output-template-file package.yaml
      - uses: actions/upload-artifact@v2
        with:
          name: package.yaml
          path: package.yaml
  deploy:
    if: github.ref == 'refs/heads/main'
    environment: dev
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${env.REGION}
      - uses: aws-actions/setup-sam@v1
      - uses: actions/dowload-artifact@v2
        with:
          name: package.yaml
          path: package.yaml
      - name: deploy to the aws cloud
        run: |
          sam deploy --stack-name ${TESTING_STACK_NAME} \
          --template package.yaml \
          --capabilities CAPABILITY_IAM \
          --region ${REGION} \
          --s3-bucket ${TESTING_ARTIFACTS_BUCKET} \
          --no-fail-on-empty-changeset 
