name: AWS SAM CI/CD Workflow
on: push
env:
  mascot: Mona
  super_duper_var: totally_awesome

jobs:
  sam-validate:
    environment: dev
    runs-on: ubuntu-latest
    env:
      mascot: Tux
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1
      - uses: aws-actions/setup-sam@v1
      - run: sam validate -t template.json
