name: AWS SAM CI/CD Workflow
on: push
env:
  mascot: Mona
  super_duper_var: totally_awesome

jobs:
  sam-validate:
    runs-on: ubuntu-latest
    env:
      mascot: Tux
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - uses: aws-actions/setup-sam@v1
      - run: sam validate -t template.json
